# Device name that's shown in the "WhatsApp Web" section in the mobile app.
os_name: WhatsApp-Cloud bridge

# Displayname template for WhatsApp users.
# {{.PushName}}     - nickname set by the WhatsApp user
# {{.BusinessName}} - validated WhatsApp business name
# {{.Phone}}        - phone number (international format)
# {{.FullName}}     - Name you set in the contacts list
displayname_template: "{{or .BusinessName .PushName .Phone}} (WA)"

# Should sending WhatsApp status messages be allowed?
# This can cause issues if the user has lots of contacts, so it's disabled by default.
disable_status_broadcast_send: true