# Device name that's shown in the "WhatsApp Web" section in the mobile app.
os_name: WhatsApp-Cloud bridge

# Displayname template for WhatsApp users.
# {{.PushName}}     - nickname set by the WhatsApp user
# {{.BusinessName}} - validated WhatsApp business name
# {{.Phone}}        - phone number (international format)
# {{.FullName}}     - Name you set in the contacts list
displayname_template: "{{or .BusinessName .PushName .Phone}} (WA)"

# Should sending WhatsApp status messages be allowed?
# This can cause issues if the user has lots of contacts, so it's disabled by default.
disable_status_broadcast_send: true

# Default user level for the WhatsApp rooms.
default_user_level: 9001

# Default power levels for the WhatsApp rooms.
# These are used when creating new rooms.
# The values are the same as in the Matrix spec:
default_power_levels:
  events_default: 0
  users_default: 0
  state_default: 0
  redact: 99
  ban: 99
  kick: 99
  invite: 99

# Default events levels for the WhatsApp rooms.
# These are used when creating new rooms.
# The values are the same as in the Matrix spec:
default_events_levels:
  reaction: 0
  room_name: 0
  room_avatar: 0
  room_topic: 0
  room_encryption: 99
  room_tombstone: 99

whatsapp:
    # Whatsapp base URL
    base_url: https://graph.facebook.com
    version: v17.0
    # Path prefix for webhook endpoints. Subpaths are /status and /receive.
    # Note that the webhook must be put behind a reverse proxy with https.
    webhook_path: /cloud
    # Endpoint for sending to approve template
    template_path: /message_templates
    file_name: Archivo

    # Dict of error codes and and their reasons
    error_codes:
        1000:
            reason_en: File format unsupported
            reason_es: Tipo de archivo no aceptado
        1001:
            reason_en: "Last Mapped Bot Details And Sender Details Mismatch"
            reason_es: "Los detalles del último bot asignado y los detalles del remitente no coinciden"
        1002:
            reason_en: "Number Does Not Exists On WhatsApp"
            reason_es: "El número no existe en WhatsApp"
        1003:
            reason_en: "Unable To Send Message | Check your wallet balance"
            reason_es: "Envío de mensajes inhabilitado | Verifica tu saldo en plataforma"
        1004:
            reason_en: "Message sending failed as user is inactive for session message and template messaging is disabled"
            reason_es: "Falló el envío del mensaje porque el usuario está inactivo para una sesión de mensajes y el envío de plantillas está desactivado"
        1005:
            reason_en: "Message sending failed as user is inactive for session message and template did not match"
            reason_es: "Mensaje no entregado, por favor intente nuevamente. Verifique que no hayan pasado más de 24 horas desde el último mensaje."
        1006:
            reason_en: "Message sending failed as user is inactive for session message and not opted in for template message"
            reason_es: "Falló el envío del mensaje porque el usuario está inactivo para una sesión de mensajes y no está habilitado para recibir plantillas"
        1007:
            reason_en: "Message sending failed as user is inactive for session message, not opted in for template message and template did not match"
            reason_es: "Falló el envío del mensaje porque el usuario está inactivo para una sesión de mensajes, no está habilitado para recibir plantillas, y el mensaje no coincidió con una plantilla"
        1008:
            reason_en: "User is not Opted in and Inactive"
            reason_es: "Usuario no habilitado para recibir mensajes e inactivo"
        1010:
            reason_en: "Invalid Media Url"
            reason_es: "URL de multimedia inválida"
        1011:
            reason_en: "Invalid Media Size"
            reason_es: "Tamaño de multimedia inválido"